---
kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install-dependencies
    image: node:1.12-alpine
    commands:
      - yarn -s --frozen-lockfile

  - name: lint
    image: node:1.12-alpine
    commands:
      - yarn lint

  - name: test
    image: node:1.12-alpine
    commands:
      - yarn test

  - name: build
    image: node:1.12-alpine
    commands:
      - GATSBY_ENV=Development yarn gatsby build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache
# pipeline:
#   restore-cache:
#     image: drillster/drone-volume-cache
#     restore: true
#     mount:
#       - ./node_modules
#       - ./public
#       - ./.cache
#     volumes:
#       - /tmp/cache:/cache

#   install-dependencies:
#     image: node:latest
#     commands:
#       - yarn install

#   lint:
#     image: node:latest
#     commands:
#       - yarn lint

#   build-site:
#     image: node:latest
#     commands:
#       - yarn build:ci

#   rebuild-cache:
#     image: drillster/drone-volume-cache
#     rebuild: true
#     mount:
#       - ./node_modules
#       - ./public
#       - ./.cache
#     volumes:
#       - /tmp/cache:/cache
