---
pipeline:

  # restore-cache:
  #   image: drillster/drone-volume-cache
  #   restore: true
  #   mount:
  #     - ./node_modules
  #     - ./public
  #     - ./.cache
  #   volumes:
  #     - /tmp/cache:/cache

  install-dependencies:
    image: node:latest
    commands:
      - yarn install

  lint:
    image: node:latest
    commands:
      - yarn lint

  build-site:
    image: node:latest
    commands:
      - yarn build:ci

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./public
      - ./.cache
    volumes:
      - /tmp/cache:/cache
