kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install-dependencies
    image: node:12-alpine
    commands:
      - yarn -s --frozen-lockfile

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: lint
    image: node:12-alpine
    commands:
      - yarn lint

  - name: test
    image: node:12-alpine
    commands:
      - yarn test

  - name: build
    image: node:12-alpine
    commands:
      - GATSBY_ENV=Development yarn gatsby build

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache
