---
pipeline:

  # restore-cache:
  #   image: drillster/drone-volume-cache
  #   restore: true
  #   mount:
  #     - ./node_modules
  #   volumes:
  #     - /tmp/cache:/cache

  install-dependencies:
    image: node:9
    commands:
      - yarn install

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  lint:
    image: node:9
    commands:
      - yarn lint

  build-site:
    image: node:9
    commands:
      - yarn build
