---
pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install-dependencies:
    image: node
    commands:
      - yarn install

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  lint:
    image: node
    commands:
      - yarn lint

  build-site:
    image: node
    commands:
      - yarn build
