// flow-typed signature: 1ce8df9bf0265e2c6de3da7b8fb44f09
// flow-typed version: <<STUB>>/copy-files_v^0.1.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-files'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-files' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-files/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-files/index' {
  declare module.exports: $Exports<'copy-files'>;
}
declare module 'copy-files/index.js' {
  declare module.exports: $Exports<'copy-files'>;
}
declare module 'copy-files/test/index.js' {
  declare module.exports: $Exports<'copy-files/test/index'>;
}
