// flow-typed signature: 88dc5572220da830c9e913639c993f8b
// flow-typed version: <<STUB>>/copy-paste_v^1.3.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-paste'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-paste' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-paste/platform/darwin' {
  declare module.exports: any;
}

declare module 'copy-paste/platform/linux' {
  declare module.exports: any;
}

declare module 'copy-paste/platform/win32' {
  declare module.exports: any;
}

declare module 'copy-paste/test/copypaste' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-paste/index' {
  declare module.exports: $Exports<'copy-paste'>;
}
declare module 'copy-paste/index.js' {
  declare module.exports: $Exports<'copy-paste'>;
}
declare module 'copy-paste/platform/darwin.js' {
  declare module.exports: $Exports<'copy-paste/platform/darwin'>;
}
declare module 'copy-paste/platform/linux.js' {
  declare module.exports: $Exports<'copy-paste/platform/linux'>;
}
declare module 'copy-paste/platform/win32.js' {
  declare module.exports: $Exports<'copy-paste/platform/win32'>;
}
declare module 'copy-paste/test/copypaste.js' {
  declare module.exports: $Exports<'copy-paste/test/copypaste'>;
}
