// flow-typed signature: 2013a6c88a38f2c480c9bd4911735d2b
// flow-typed version: <<STUB>>/differencify_v^1.3.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'differencify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'differencify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'differencify/dist/compareImage' {
  declare module.exports: any;
}

declare module 'differencify/dist/config/defaultConfigs' {
  declare module.exports: any;
}

declare module 'differencify/dist/freezeImage' {
  declare module.exports: any;
}

declare module 'differencify/dist/helpers/functions' {
  declare module.exports: any;
}

declare module 'differencify/dist/helpers/functionToString' {
  declare module.exports: any;
}

declare module 'differencify/dist/helpers/moduleList' {
  declare module.exports: any;
}

declare module 'differencify/dist/helpers/proxyChain' {
  declare module.exports: any;
}

declare module 'differencify/dist/index' {
  declare module.exports: any;
}

declare module 'differencify/dist/sanitiser' {
  declare module.exports: any;
}

declare module 'differencify/dist/target' {
  declare module.exports: any;
}

declare module 'differencify/dist/utils/jestMatchers' {
  declare module.exports: any;
}

declare module 'differencify/dist/utils/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'differencify/dist/compareImage.js' {
  declare module.exports: $Exports<'differencify/dist/compareImage'>;
}
declare module 'differencify/dist/config/defaultConfigs.js' {
  declare module.exports: $Exports<'differencify/dist/config/defaultConfigs'>;
}
declare module 'differencify/dist/freezeImage.js' {
  declare module.exports: $Exports<'differencify/dist/freezeImage'>;
}
declare module 'differencify/dist/helpers/functions.js' {
  declare module.exports: $Exports<'differencify/dist/helpers/functions'>;
}
declare module 'differencify/dist/helpers/functionToString.js' {
  declare module.exports: $Exports<'differencify/dist/helpers/functionToString'>;
}
declare module 'differencify/dist/helpers/moduleList.js' {
  declare module.exports: $Exports<'differencify/dist/helpers/moduleList'>;
}
declare module 'differencify/dist/helpers/proxyChain.js' {
  declare module.exports: $Exports<'differencify/dist/helpers/proxyChain'>;
}
declare module 'differencify/dist/index.js' {
  declare module.exports: $Exports<'differencify/dist/index'>;
}
declare module 'differencify/dist/sanitiser.js' {
  declare module.exports: $Exports<'differencify/dist/sanitiser'>;
}
declare module 'differencify/dist/target.js' {
  declare module.exports: $Exports<'differencify/dist/target'>;
}
declare module 'differencify/dist/utils/jestMatchers.js' {
  declare module.exports: $Exports<'differencify/dist/utils/jestMatchers'>;
}
declare module 'differencify/dist/utils/logger.js' {
  declare module.exports: $Exports<'differencify/dist/utils/logger'>;
}
