// flow-typed signature: 1cb9662dfed8a2230146aff6a5b5d5d1
// flow-typed version: <<STUB>>/gatsby-source-filesystem_v^1.5.11/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-source-filesystem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-source-filesystem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-source-filesystem/create-file-node' {
  declare module.exports: any;
}

declare module 'gatsby-source-filesystem/create-file-path' {
  declare module.exports: any;
}

declare module 'gatsby-source-filesystem/create-remote-file-node' {
  declare module.exports: any;
}

declare module 'gatsby-source-filesystem/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-source-filesystem/create-file-node.js' {
  declare module.exports: $Exports<'gatsby-source-filesystem/create-file-node'>;
}
declare module 'gatsby-source-filesystem/create-file-path.js' {
  declare module.exports: $Exports<'gatsby-source-filesystem/create-file-path'>;
}
declare module 'gatsby-source-filesystem/create-remote-file-node.js' {
  declare module.exports: $Exports<'gatsby-source-filesystem/create-remote-file-node'>;
}
declare module 'gatsby-source-filesystem/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-source-filesystem/gatsby-node'>;
}
declare module 'gatsby-source-filesystem/index' {
  declare module.exports: $Exports<'gatsby-source-filesystem'>;
}
declare module 'gatsby-source-filesystem/index.js' {
  declare module.exports: $Exports<'gatsby-source-filesystem'>;
}
