// flow-typed signature: 1353517e2c704ba8bb38e5dfbe954f49
// flow-typed version: <<STUB>>/gatsby-plugin-react-css-modules_v^1.0.11/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-react-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-react-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-react-css-modules/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-react-css-modules/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-css-modules/gatsby-node'>;
}
declare module 'gatsby-plugin-react-css-modules/index' {
  declare module.exports: $Exports<'gatsby-plugin-react-css-modules'>;
}
declare module 'gatsby-plugin-react-css-modules/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-css-modules'>;
}
