// flow-typed signature: 2a854a173a814415e7f33e54a3f736de
// flow-typed version: <<STUB>>/hamburgers_v^0.9.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hamburgers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hamburgers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hamburgers/bs-config' {
  declare module.exports: any;
}

declare module 'hamburgers/eyeglass-exports' {
  declare module.exports: any;
}

declare module 'hamburgers/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hamburgers/bs-config.js' {
  declare module.exports: $Exports<'hamburgers/bs-config'>;
}
declare module 'hamburgers/eyeglass-exports.js' {
  declare module.exports: $Exports<'hamburgers/eyeglass-exports'>;
}
declare module 'hamburgers/gulpfile.js' {
  declare module.exports: $Exports<'hamburgers/gulpfile'>;
}
declare module 'hamburgers/index' {
  declare module.exports: $Exports<'hamburgers'>;
}
declare module 'hamburgers/index.js' {
  declare module.exports: $Exports<'hamburgers'>;
}
