// flow-typed signature: 131ce3b3f7161a722a947b1408eb55b1
// flow-typed version: <<STUB>>/react-with-available-width_v^2.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-available-width'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-available-width' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-available-width/dist/withAvailableWidth' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-available-width/dist/withAvailableWidth.js' {
  declare module.exports: $Exports<'react-with-available-width/dist/withAvailableWidth'>;
}
