// flow-typed signature: 50429535c0e7c8e7272b11d324259345
// flow-typed version: <<STUB>>/react-sizes_v^0.4.3/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sizes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sizes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sizes/dist/react-sizes.min' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/createSizedComponent' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/index' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/presets' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/utils/getWindowSizes' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/utils/shallowDiff' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/withSizes' {
  declare module.exports: any;
}

declare module 'react-sizes/src/createSizedComponent' {
  declare module.exports: any;
}

declare module 'react-sizes/src/index' {
  declare module.exports: any;
}

declare module 'react-sizes/src/presets' {
  declare module.exports: any;
}

declare module 'react-sizes/src/utils/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-sizes/src/utils/getWindowSizes' {
  declare module.exports: any;
}

declare module 'react-sizes/src/utils/shallowDiff' {
  declare module.exports: any;
}

declare module 'react-sizes/src/withSizes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sizes/dist/react-sizes.min.js' {
  declare module.exports: $Exports<'react-sizes/dist/react-sizes.min'>;
}
declare module 'react-sizes/lib/createSizedComponent.js' {
  declare module.exports: $Exports<'react-sizes/lib/createSizedComponent'>;
}
declare module 'react-sizes/lib/index.js' {
  declare module.exports: $Exports<'react-sizes/lib/index'>;
}
declare module 'react-sizes/lib/presets.js' {
  declare module.exports: $Exports<'react-sizes/lib/presets'>;
}
declare module 'react-sizes/lib/utils/getDisplayName.js' {
  declare module.exports: $Exports<'react-sizes/lib/utils/getDisplayName'>;
}
declare module 'react-sizes/lib/utils/getWindowSizes.js' {
  declare module.exports: $Exports<'react-sizes/lib/utils/getWindowSizes'>;
}
declare module 'react-sizes/lib/utils/shallowDiff.js' {
  declare module.exports: $Exports<'react-sizes/lib/utils/shallowDiff'>;
}
declare module 'react-sizes/lib/withSizes.js' {
  declare module.exports: $Exports<'react-sizes/lib/withSizes'>;
}
declare module 'react-sizes/src/createSizedComponent.js' {
  declare module.exports: $Exports<'react-sizes/src/createSizedComponent'>;
}
declare module 'react-sizes/src/index.js' {
  declare module.exports: $Exports<'react-sizes/src/index'>;
}
declare module 'react-sizes/src/presets.js' {
  declare module.exports: $Exports<'react-sizes/src/presets'>;
}
declare module 'react-sizes/src/utils/getDisplayName.js' {
  declare module.exports: $Exports<'react-sizes/src/utils/getDisplayName'>;
}
declare module 'react-sizes/src/utils/getWindowSizes.js' {
  declare module.exports: $Exports<'react-sizes/src/utils/getWindowSizes'>;
}
declare module 'react-sizes/src/utils/shallowDiff.js' {
  declare module.exports: $Exports<'react-sizes/src/utils/shallowDiff'>;
}
declare module 'react-sizes/src/withSizes.js' {
  declare module.exports: $Exports<'react-sizes/src/withSizes'>;
}
