// flow-typed signature: 479fc12358a54e0088b51fb743ce3721
// flow-typed version: <<STUB>>/react-cosmos_v^3.2.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cosmos'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cosmos' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cosmos/bin/cosmos-export' {
  declare module.exports: any;
}

declare module 'react-cosmos/bin/cosmos' {
  declare module.exports: any;
}

declare module 'react-cosmos/bin/print-fixture-files' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/client/loader-entry' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/client/mount' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/client/react-devtools-hook' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/client/react-error-overlay' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/client/user-modules' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/server/default-webpack-config' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/server/embed-modules-webpack-loader' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/server/export' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/server/extend-webpack-config' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/server/playground-html' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/server/print-fixture-files' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/server/server' {
  declare module.exports: any;
}

declare module 'react-cosmos/lib/server/user-webpack-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cosmos/bin/cosmos-export.js' {
  declare module.exports: $Exports<'react-cosmos/bin/cosmos-export'>;
}
declare module 'react-cosmos/bin/cosmos.js' {
  declare module.exports: $Exports<'react-cosmos/bin/cosmos'>;
}
declare module 'react-cosmos/bin/print-fixture-files.js' {
  declare module.exports: $Exports<'react-cosmos/bin/print-fixture-files'>;
}
declare module 'react-cosmos/lib/client/loader-entry.js' {
  declare module.exports: $Exports<'react-cosmos/lib/client/loader-entry'>;
}
declare module 'react-cosmos/lib/client/mount.js' {
  declare module.exports: $Exports<'react-cosmos/lib/client/mount'>;
}
declare module 'react-cosmos/lib/client/react-devtools-hook.js' {
  declare module.exports: $Exports<'react-cosmos/lib/client/react-devtools-hook'>;
}
declare module 'react-cosmos/lib/client/react-error-overlay.js' {
  declare module.exports: $Exports<'react-cosmos/lib/client/react-error-overlay'>;
}
declare module 'react-cosmos/lib/client/user-modules.js' {
  declare module.exports: $Exports<'react-cosmos/lib/client/user-modules'>;
}
declare module 'react-cosmos/lib/server/default-webpack-config.js' {
  declare module.exports: $Exports<'react-cosmos/lib/server/default-webpack-config'>;
}
declare module 'react-cosmos/lib/server/embed-modules-webpack-loader.js' {
  declare module.exports: $Exports<'react-cosmos/lib/server/embed-modules-webpack-loader'>;
}
declare module 'react-cosmos/lib/server/export.js' {
  declare module.exports: $Exports<'react-cosmos/lib/server/export'>;
}
declare module 'react-cosmos/lib/server/extend-webpack-config.js' {
  declare module.exports: $Exports<'react-cosmos/lib/server/extend-webpack-config'>;
}
declare module 'react-cosmos/lib/server/playground-html.js' {
  declare module.exports: $Exports<'react-cosmos/lib/server/playground-html'>;
}
declare module 'react-cosmos/lib/server/print-fixture-files.js' {
  declare module.exports: $Exports<'react-cosmos/lib/server/print-fixture-files'>;
}
declare module 'react-cosmos/lib/server/server.js' {
  declare module.exports: $Exports<'react-cosmos/lib/server/server'>;
}
declare module 'react-cosmos/lib/server/user-webpack-config.js' {
  declare module.exports: $Exports<'react-cosmos/lib/server/user-webpack-config'>;
}
