// flow-typed signature: 8b48f767f0d416b73a7d9f4d8918ad2a
// flow-typed version: <<STUB>>/react-calendar-heatmap_v^1.6.3/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-calendar-heatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-calendar-heatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-calendar-heatmap/build/index' {
  declare module.exports: any;
}

declare module 'react-calendar-heatmap/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-calendar-heatmap/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-calendar-heatmap/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-calendar-heatmap/build/index.js' {
  declare module.exports: $Exports<'react-calendar-heatmap/build/index'>;
}
declare module 'react-calendar-heatmap/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-calendar-heatmap/coverage/lcov-report/prettify'>;
}
declare module 'react-calendar-heatmap/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-calendar-heatmap/coverage/lcov-report/sorter'>;
}
declare module 'react-calendar-heatmap/webpack.config.js' {
  declare module.exports: $Exports<'react-calendar-heatmap/webpack.config'>;
}
