// flow-typed signature: 55dae8565c9f0e967ed6e2fa8aa381e7
// flow-typed version: <<STUB>>/serve_v^6.4.3/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serve/bin/serve' {
  declare module.exports: any;
}

declare module 'serve/lib/api' {
  declare module.exports: any;
}

declare module 'serve/lib/listening' {
  declare module.exports: any;
}

declare module 'serve/lib/options' {
  declare module.exports: any;
}

declare module 'serve/lib/render' {
  declare module.exports: any;
}

declare module 'serve/lib/server' {
  declare module.exports: any;
}

declare module 'serve/lib/view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serve/bin/serve.js' {
  declare module.exports: $Exports<'serve/bin/serve'>;
}
declare module 'serve/lib/api.js' {
  declare module.exports: $Exports<'serve/lib/api'>;
}
declare module 'serve/lib/listening.js' {
  declare module.exports: $Exports<'serve/lib/listening'>;
}
declare module 'serve/lib/options.js' {
  declare module.exports: $Exports<'serve/lib/options'>;
}
declare module 'serve/lib/render.js' {
  declare module.exports: $Exports<'serve/lib/render'>;
}
declare module 'serve/lib/server.js' {
  declare module.exports: $Exports<'serve/lib/server'>;
}
declare module 'serve/lib/view.js' {
  declare module.exports: $Exports<'serve/lib/view'>;
}
