// flow-typed signature: a0d2e4701865de63049999e5514862d1
// flow-typed version: <<STUB>>/tachyons-modules_v^1.1.10/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tachyons-modules/index' {
  declare module.exports: $Exports<'tachyons-modules'>;
}
declare module 'tachyons-modules/index.js' {
  declare module.exports: $Exports<'tachyons-modules'>;
}
