// flow-typed signature: 2bf65b3843217747f26d714ea0bccb0d
// flow-typed version: <<STUB>>/tachyons-colors_v^5.3.3/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-colors' {
  declare module.exports: any;
}
