// flow-typed signature: 85c40e21c6cc0db39390f6b7793067d8
// flow-typed version: <<STUB>>/textlint-rule-diacritics_v^0.0.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint-rule-diacritics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint-rule-diacritics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'textlint-rule-diacritics/index' {
  declare module.exports: $Exports<'textlint-rule-diacritics'>;
}
declare module 'textlint-rule-diacritics/index.js' {
  declare module.exports: $Exports<'textlint-rule-diacritics'>;
}
