// flow-typed signature: b40fde50fdf5a7975b312895cf3fd26f
// flow-typed version: <<STUB>>/textlint-rule-en-capitalization_v^2.0.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint-rule-en-capitalization'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint-rule-en-capitalization' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'textlint-rule-en-capitalization/lib/captalize' {
  declare module.exports: any;
}

declare module 'textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization' {
  declare module.exports: any;
}

declare module 'textlint-rule-en-capitalization/src/captalize' {
  declare module.exports: any;
}

declare module 'textlint-rule-en-capitalization/src/textlint-rule-en-capitalization' {
  declare module.exports: any;
}

// Filename aliases
declare module 'textlint-rule-en-capitalization/lib/captalize.js' {
  declare module.exports: $Exports<'textlint-rule-en-capitalization/lib/captalize'>;
}
declare module 'textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js' {
  declare module.exports: $Exports<'textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization'>;
}
declare module 'textlint-rule-en-capitalization/src/captalize.js' {
  declare module.exports: $Exports<'textlint-rule-en-capitalization/src/captalize'>;
}
declare module 'textlint-rule-en-capitalization/src/textlint-rule-en-capitalization.js' {
  declare module.exports: $Exports<'textlint-rule-en-capitalization/src/textlint-rule-en-capitalization'>;
}
