// flow-typed signature: 13bc4ad597ce3c710d0edf56ab877a1b
// flow-typed version: <<STUB>>/textlint-rule-no-start-duplicated-conjunction_v^2.0.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint-rule-no-start-duplicated-conjunction'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint-rule-no-start-duplicated-conjunction' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'textlint-rule-no-start-duplicated-conjunction/lib/no-start-duplicated-conjunction' {
  declare module.exports: any;
}

declare module 'textlint-rule-no-start-duplicated-conjunction/src/no-start-duplicated-conjunction' {
  declare module.exports: any;
}

// Filename aliases
declare module 'textlint-rule-no-start-duplicated-conjunction/lib/no-start-duplicated-conjunction.js' {
  declare module.exports: $Exports<'textlint-rule-no-start-duplicated-conjunction/lib/no-start-duplicated-conjunction'>;
}
declare module 'textlint-rule-no-start-duplicated-conjunction/src/no-start-duplicated-conjunction.js' {
  declare module.exports: $Exports<'textlint-rule-no-start-duplicated-conjunction/src/no-start-duplicated-conjunction'>;
}
