// flow-typed signature: 9d651763a2badf27f3d015a9a7c626bd
// flow-typed version: <<STUB>>/textlint-rule-terminology_v^1.1.27/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint-rule-terminology'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint-rule-terminology' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'textlint-rule-terminology/index' {
  declare module.exports: $Exports<'textlint-rule-terminology'>;
}
declare module 'textlint-rule-terminology/index.js' {
  declare module.exports: $Exports<'textlint-rule-terminology'>;
}
