// flow-typed signature: ec7d5bd529521246fdc1273c4911da7f
// flow-typed version: <<STUB>>/textlint_v^10.1.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'textlint/bin/textlint' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/cli' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/config/config-initializer' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/config/config-loader' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/config/config' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/config/plugin-loader' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/config/preset-loader' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/config/separate-by-config-option' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/core/plugin-creator-set' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/core/rule-creator-helper' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/core/rule-creator-set' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/execute-file-backer-manager' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/execute-file-backers/abstruct-backer' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/execute-file-backers/cache-backer' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/processor-map' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/rule-loader' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/rule-map' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/textlint-engine-core' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/textlint-module-loader' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/textlint-module-mapper' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/engine/textlint-module-resolver' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/fixer/textlint-fixer' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/index' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/options' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/shared/type/MessageType' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/shared/type/SeverityLevel' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/textfix-engine' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/textlint-core' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/textlint-engine' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/textlint-interface' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/textlint' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/util/config-util' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/util/find-util' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/util/fs-promise' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/util/logger' {
  declare module.exports: any;
}

declare module 'textlint/lib/textlint/src/util/traverse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'textlint/bin/textlint.js' {
  declare module.exports: $Exports<'textlint/bin/textlint'>;
}
declare module 'textlint/lib/textlint/src/cli.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/cli'>;
}
declare module 'textlint/lib/textlint/src/config/config-initializer.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/config/config-initializer'>;
}
declare module 'textlint/lib/textlint/src/config/config-loader.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/config/config-loader'>;
}
declare module 'textlint/lib/textlint/src/config/config.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/config/config'>;
}
declare module 'textlint/lib/textlint/src/config/plugin-loader.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/config/plugin-loader'>;
}
declare module 'textlint/lib/textlint/src/config/preset-loader.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/config/preset-loader'>;
}
declare module 'textlint/lib/textlint/src/config/separate-by-config-option.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/config/separate-by-config-option'>;
}
declare module 'textlint/lib/textlint/src/core/plugin-creator-set.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/core/plugin-creator-set'>;
}
declare module 'textlint/lib/textlint/src/core/rule-creator-helper.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/core/rule-creator-helper'>;
}
declare module 'textlint/lib/textlint/src/core/rule-creator-set.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/core/rule-creator-set'>;
}
declare module 'textlint/lib/textlint/src/engine/execute-file-backer-manager.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/execute-file-backer-manager'>;
}
declare module 'textlint/lib/textlint/src/engine/execute-file-backers/abstruct-backer.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/execute-file-backers/abstruct-backer'>;
}
declare module 'textlint/lib/textlint/src/engine/execute-file-backers/cache-backer.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/execute-file-backers/cache-backer'>;
}
declare module 'textlint/lib/textlint/src/engine/processor-map.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/processor-map'>;
}
declare module 'textlint/lib/textlint/src/engine/rule-loader.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/rule-loader'>;
}
declare module 'textlint/lib/textlint/src/engine/rule-map.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/rule-map'>;
}
declare module 'textlint/lib/textlint/src/engine/textlint-engine-core.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/textlint-engine-core'>;
}
declare module 'textlint/lib/textlint/src/engine/textlint-module-loader.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/textlint-module-loader'>;
}
declare module 'textlint/lib/textlint/src/engine/textlint-module-mapper.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/textlint-module-mapper'>;
}
declare module 'textlint/lib/textlint/src/engine/textlint-module-resolver.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/engine/textlint-module-resolver'>;
}
declare module 'textlint/lib/textlint/src/fixer/textlint-fixer.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/fixer/textlint-fixer'>;
}
declare module 'textlint/lib/textlint/src/index.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/index'>;
}
declare module 'textlint/lib/textlint/src/options.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/options'>;
}
declare module 'textlint/lib/textlint/src/shared/type/MessageType.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/shared/type/MessageType'>;
}
declare module 'textlint/lib/textlint/src/shared/type/SeverityLevel.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/shared/type/SeverityLevel'>;
}
declare module 'textlint/lib/textlint/src/textfix-engine.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/textfix-engine'>;
}
declare module 'textlint/lib/textlint/src/textlint-core.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/textlint-core'>;
}
declare module 'textlint/lib/textlint/src/textlint-engine.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/textlint-engine'>;
}
declare module 'textlint/lib/textlint/src/textlint-interface.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/textlint-interface'>;
}
declare module 'textlint/lib/textlint/src/textlint.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/textlint'>;
}
declare module 'textlint/lib/textlint/src/util/config-util.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/util/config-util'>;
}
declare module 'textlint/lib/textlint/src/util/find-util.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/util/find-util'>;
}
declare module 'textlint/lib/textlint/src/util/fs-promise.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/util/fs-promise'>;
}
declare module 'textlint/lib/textlint/src/util/logger.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/util/logger'>;
}
declare module 'textlint/lib/textlint/src/util/traverse.js' {
  declare module.exports: $Exports<'textlint/lib/textlint/src/util/traverse'>;
}
