// flow-typed signature: 76e1c7adc0bceb13f389bb4c82fee837
// flow-typed version: <<STUB>>/textlint-rule-rousseau_v^1.4.5/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint-rule-rousseau'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint-rule-rousseau' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'textlint-rule-rousseau/lib/textlint-rule-rousseau' {
  declare module.exports: any;
}

declare module 'textlint-rule-rousseau/src/textlint-rule-rousseau' {
  declare module.exports: any;
}

// Filename aliases
declare module 'textlint-rule-rousseau/lib/textlint-rule-rousseau.js' {
  declare module.exports: $Exports<'textlint-rule-rousseau/lib/textlint-rule-rousseau'>;
}
declare module 'textlint-rule-rousseau/src/textlint-rule-rousseau.js' {
  declare module.exports: $Exports<'textlint-rule-rousseau/src/textlint-rule-rousseau'>;
}
