// flow-typed signature: e031937285c06b74910f34ddd500d917
// flow-typed version: <<STUB>>/textlint-rule-no-dead-link_v^4.1.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint-rule-no-dead-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint-rule-no-dead-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'textlint-rule-no-dead-link/lib/no-dead-link' {
  declare module.exports: any;
}

declare module 'textlint-rule-no-dead-link/src/no-dead-link' {
  declare module.exports: any;
}

// Filename aliases
declare module 'textlint-rule-no-dead-link/lib/no-dead-link.js' {
  declare module.exports: $Exports<'textlint-rule-no-dead-link/lib/no-dead-link'>;
}
declare module 'textlint-rule-no-dead-link/src/no-dead-link.js' {
  declare module.exports: $Exports<'textlint-rule-no-dead-link/src/no-dead-link'>;
}
