// flow-typed signature: fb5ca884bb4225e37c06685737610edc
// flow-typed version: <<STUB>>/textlint-rule-apostrophe_v^1.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint-rule-apostrophe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint-rule-apostrophe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'textlint-rule-apostrophe/index' {
  declare module.exports: $Exports<'textlint-rule-apostrophe'>;
}
declare module 'textlint-rule-apostrophe/index.js' {
  declare module.exports: $Exports<'textlint-rule-apostrophe'>;
}
