// flow-typed signature: 8ad9be394553aa43ed350ebf5bf7c6a8
// flow-typed version: <<STUB>>/textlint-rule-stop-words_v^1.0.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textlint-rule-stop-words'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textlint-rule-stop-words' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'textlint-rule-stop-words/index' {
  declare module.exports: $Exports<'textlint-rule-stop-words'>;
}
declare module 'textlint-rule-stop-words/index.js' {
  declare module.exports: $Exports<'textlint-rule-stop-words'>;
}
