// flow-typed signature: 4ea15df6d3e76fc2c08d03825dca6493
// flow-typed version: <<STUB>>/twemoji_v^2.5.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twemoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twemoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twemoji/2/twemoji.amd' {
  declare module.exports: any;
}

declare module 'twemoji/2/twemoji' {
  declare module.exports: any;
}

declare module 'twemoji/2/twemoji.min' {
  declare module.exports: any;
}

declare module 'twemoji/2/twemoji.npm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twemoji/2/twemoji.amd.js' {
  declare module.exports: $Exports<'twemoji/2/twemoji.amd'>;
}
declare module 'twemoji/2/twemoji.js' {
  declare module.exports: $Exports<'twemoji/2/twemoji'>;
}
declare module 'twemoji/2/twemoji.min.js' {
  declare module.exports: $Exports<'twemoji/2/twemoji.min'>;
}
declare module 'twemoji/2/twemoji.npm.js' {
  declare module.exports: $Exports<'twemoji/2/twemoji.npm'>;
}
