// flow-typed signature: 6e944c8b53c514a956876e03e2f51b18
// flow-typed version: <<STUB>>/typeface-montserrat_v^0.0.45/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-montserrat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-montserrat' {
  declare module.exports: any;
}
