// flow-typed signature: 40d47a04a132969770e2235880e63f64
// flow-typed version: <<STUB>>/typeface-lato_v^0.0.44/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-lato'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-lato' {
  declare module.exports: any;
}
