// flow-typed signature: ce49988289d161955d462c322060b0b8
// flow-typed version: <<STUB>>/typeface-spectral_v^0.0.44/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-spectral'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-spectral' {
  declare module.exports: any;
}
