// flow-typed signature: 84b9f6b44934c4cbb875be5957dfa341
// flow-typed version: <<STUB>>/typeface-open-sans_v^0.0.45/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-open-sans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-open-sans' {
  declare module.exports: any;
}
