// flow-typed signature: db1e7cf90759aff68d7b1690fc6f8b26
// flow-typed version: <<STUB>>/typeface-source-sans-pro_v^0.0.44/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-source-sans-pro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-source-sans-pro' {
  declare module.exports: any;
}
