// flow-typed signature: d1a9351c72eb75c3ac3739e9702d20ad
// flow-typed version: <<STUB>>/typeface-poiret-one_v^0.0.44/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-poiret-one'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-poiret-one' {
  declare module.exports: any;
}
