// flow-typed signature: ed16c8b709b9fc38906ecfab80ee19bb
// flow-typed version: <<STUB>>/typography_v^0.16.6/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typography' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typography/dist/client' {
  declare module.exports: any;
}

declare module 'typography/dist/index' {
  declare module.exports: any;
}

declare module 'typography/dist/utils/compileStyles' {
  declare module.exports: any;
}

declare module 'typography/dist/utils/constants' {
  declare module.exports: any;
}

declare module 'typography/dist/utils/createStyles' {
  declare module.exports: any;
}

declare module 'typography/dist/utils/normalize' {
  declare module.exports: any;
}

declare module 'typography/src/client' {
  declare module.exports: any;
}

declare module 'typography/src/index' {
  declare module.exports: any;
}

declare module 'typography/src/utils/compileStyles' {
  declare module.exports: any;
}

declare module 'typography/src/utils/createStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typography/dist/client.js' {
  declare module.exports: $Exports<'typography/dist/client'>;
}
declare module 'typography/dist/index.js' {
  declare module.exports: $Exports<'typography/dist/index'>;
}
declare module 'typography/dist/utils/compileStyles.js' {
  declare module.exports: $Exports<'typography/dist/utils/compileStyles'>;
}
declare module 'typography/dist/utils/constants.js' {
  declare module.exports: $Exports<'typography/dist/utils/constants'>;
}
declare module 'typography/dist/utils/createStyles.js' {
  declare module.exports: $Exports<'typography/dist/utils/createStyles'>;
}
declare module 'typography/dist/utils/normalize.js' {
  declare module.exports: $Exports<'typography/dist/utils/normalize'>;
}
declare module 'typography/src/client.js' {
  declare module.exports: $Exports<'typography/src/client'>;
}
declare module 'typography/src/index.js' {
  declare module.exports: $Exports<'typography/src/index'>;
}
declare module 'typography/src/utils/compileStyles.js' {
  declare module.exports: $Exports<'typography/src/utils/compileStyles'>;
}
declare module 'typography/src/utils/createStyles.js' {
  declare module.exports: $Exports<'typography/src/utils/createStyles'>;
}
