import gray from 'gray-percentage'

const colors = {
  primary: {
    // Light Primary shades --
    // autogenerated between #e4e4e4 and #ff3a5c.
    light1: '#E6D2D6',
    light2: '#E9C1C8',
    light3: '#ECB0BB',
    light4: '#EE9FAD',
    light5: '#F18FA0',
    light6: '#F47D92',
    light7: '#F66D84',
    light8: '#F95B77',
    light9: '#FC4A69',
    // Main primary.
    main: '#ff3a5c',
    // Dark Primary shades --
    // autogenerated between #333 and #ff3a5c.
    dark9: '#EA3957',
    dark8: '#D63853',
    dark7: '#C1374F',
    dark6: '#AD374B',
    dark5: '#993647',
    dark4: '#843543',
    dark3: '#70353F',
    dark2: '#5B343B',
    dark1: '#473337',
  },
  secondary: {
    // Light Primary shades --
    // autogenerated between #e4e4e4 and     #673ab7.
    light1: '#d7d2df',
    light2: '#cac1da',
    light3: '#beb0d6',
    light4: '#b19fd1',
    light5: '#a58fcd',
    light6: '#987dc8',
    light7: '#8c6dc4',
    light8: '#7f5bbf',
    light9: '#734abb',
    main: '#673ab7',
  },
  bgDark: 'rgb(55, 59, 70)',
  accent: '',
  success: '',
  warning: '',
  ui: {
    bright: '#FFC9D2',
    light: '#f5f3f7',
    whisper: '#fbfafc',
  },
  gray: {
    dark: gray(8, 270),
    copy: gray(12, 270),
    calm: gray(46, 270),
  },
}

export default colors
